### ISSUE TITLE
How to achieve the effect of curl?

### ISSUE THREAD

**Issue by weinierfei** [readium/SDKLauncher-Android#107]

**Comment by danielweck** [comment]
I'm afraid that's out of scope at the moment, so I will close the issue.

However, here's some basic guidance:

Each fixed-layout "page" is rendered on-screen using a single iframe. So a two-page spread consists in 2 separate iframes embedded within "reader.html" (i.e. the top-level document loaded inside the native webview). A "page curl" effect would have to be implemented at the level of the webview itself, so this would only work for a single FXL page. The readium-shared-js layout engine would have to be implemented natively / at the application level, in order to fully control page animation.

Each reflowable "page" actually consists in a single CSS Column within a single HTML document (hosted inside an iframe, which is embedded in the top-level webview-hosted "reader.html"). Once again, significant changes would have to be made to Readium's layout / rendering engine in order to delegate the pagination strategy to the application.

I am aware that some developers attempted to implement page-turn effects by loading multiple Readium instances within multiple embedded webview controls, but this turned into a performance bottleneck and there were peripheral issues related to prefetching / preloading content off-screen.

I hope this helps.
