### ISSUE TITLE
Readium EpubReadingSystem injection is blocking page loading

### ISSUE THREAD

**Issue by Twibit** [readium/SDKLauncher-Android#52]
Hi,

I recently updated my app to readium 0.16 and i observed a performance issue, every page load time is increased.

It seem to be related to [this line of code](https://github.com/readium/SDKLauncher-Android/blob/develop/SDKLauncher-Android/src/org/readium/sdk/android/launcher/WebViewActivity.java#L522).

I don't know why a doWait is needed here but it is blocking the whole thing for 1 second.

**Comment by danielweck** [comment]
This is a semaphore synchronization object that should get notified as soon as the javascript execution is completed:
https://github.com/readium/SDKLauncher-Android/blob/develop/SDKLauncher-Android/src/org/readium/sdk/android/launcher/WebViewActivity.java#L465
Are you testing on Kitkat+ ?
The log message (when `quiet` is false) should indicate whether or not the epubReadingSystem injection occurs quickly, or whether the 1s timeout is reached.

**Comment by Twibit** [comment]
Yes, i'm on KitKat+
In my case, the injected code only run after the timeout. 
If I mesure the time between the two logs ([here](https://github.com/readium/SDKLauncher-Android/blob/develop/SDKLauncher-Android/src/org/readium/sdk/android/launcher/WebViewActivity.java#L463) and [here](https://github.com/readium/SDKLauncher-Android/blob/develop/SDKLauncher-Android/src/org/readium/sdk/android/launcher/WebViewActivity.java#L471)), i get the same value as the timeout, even if I change it.

It looks like the semaphore is blocking the webview object.

**Comment by danielweck** [comment]
Follow-up from today's concall:

1) Jonah Dempcy @jdempcy tried to use Javascript prototypal inheritance for "attaching" the `epubReadingSystem` object to `navigator`, to no avail (this could have removed the need to manually set the `navigator.epubReadingSystem` property each time an iframe loads).

2) I tried to negate the need for `WebViewClient::shouldInterceptRequest()` in order to avoid the threading / race condition that currently prevent the semaphore (wait+notify synchronised object) from doing its job properly, resulting in the 1s timeout. Unfortunately `evaluateJavascript()` or `loadUrl()` are needed to inject the top-level `navigator.epubReadingSystem` object, because they "carry" the required top-level window execution context. Consequently, the `head` > `script` element cannot carry the Javascript code itself, it must use the `src` attribute so that the WebView can intercept the request and inject the top-level `window.navigator.epubReadingSystem` object, directly from its local context.

3) I tested both KitKat-only `evaluateJavascript()` and the generic `loadUrl()` method *without* the wait+notify semaphore, and unfortunately I could easily reproduce the missing `navigator.epubReadingSystem` object on my KitKat device, probably because of the limited performance, especially when the app process is attached to the debugger via Eclipse.

Suggested next steps:

1) Do more testing like (3) on several devices, to figure out if my hardware device (older tablet) is just a rare edge-case, or otherwise sufficiently representative to justify seeking for a "proper" solution (rather than simply removing the semaphore assuming that this will work on most devices).

2) Understand why there is a race condition in `runOnUiThread()` with the synchronised object (semaphore)...and try to fix it.

3) Capture an HTTP request-response cycle instead of using `WebViewClient::shouldInterceptRequest()`

4) Any other ideas?

**Comment by jdempcy** [comment]
I'm not entirely clear on why evaluateJavascript() or loadUrl() are needed to inject the top-level navigator.epubReadingSystem object. 

Couldn't we have an external JavaScript file called, for instance, navigator_epubreadingsystem.js, which we insert into the <head> as we do with other scripts like MathJAX?

The contents of navigator_epubreadingsystem.js would be:

    navigator.epubReadingSystem = {
      "name": "Readium SDKLauncher-Android",
      "version": "1.0.0",
      "layoutStyle": "paginated",
      "readium": {
        "buildInfo": {
            "dateTime": "Mon Jan 12 14:29:29 PST 2015",
            "version": "1.0.0",
            "gitRepositories": [{
                "name": "SDKLauncher-Android",
                "sha": "",
                "tag": "Release-0.6-114-gebd3e00",
                "clean": "false",
                "url": "https://github.com/readium/SDKLauncher-Android/tree/"
            }, {
                "name": "readium-sdk",
                "sha": "",
                "tag": "Release-0.14-146-g3987379",
                "clean": "false",
                "url": "https://github.com/readium/readium-sdk/tree/"
            }, {
                "name": "readium-shared-js",
                "sha": "",
                "tag": "Release-0.10-470-gdc921ee",
                "clean": "true",
                "url": "https://github.com/readium/readium-shared-js/tree/"
            }]
        }
      }
    }

**Comment by danielweck** [comment]
The `navigator.epubReadingSystem` object defined by the EPUB3 specification doesn't just contain "static" data, it is a Javascript object with API functions attached to it. Currently, is API is very limited (the sole function actually returns static data) so we could indeed deep-copy the `epubReadingSystem` object, and inject those clones into each loading iframe (local `window.navigator` context).

By the way, Readium inserts its own versioning data (git sha, release tag, etc.) into the `epubReadingSystem` object, but that is not part of the EPUB3 specification (we have a specially-crafted ebook that extracts and displays this data, but this is just for internal purposes, some sort of "about dialog box" in the form of an EPUB file).

So, the idea is that the `navigator.epubReadingSystem` object carries a consistent internal state, available across all loaded spine items and widget iframes. This way, any future API additions (preferably standardised by EPUB3+, but could also be Readium-specific) may include functions that read/write the (shared) state of the reading system.

On paper, this sort of makes sense. In practice, all Readium target platforms successfully manage to inject the live `navigator.epubReadingSystem` object (no clones). However, this does not "feel right", because of possible cross-origin restrictions (e.g. same-origin policy for widget iframes), and also because the shared internal state should probably be mutated via some sort of "fenced" `postMessage()` protocol, to prevent HTML EPUB content documents from hijacking the global context. 

Regardless of implementation details, there seems to be a consensus that EPUB3's `navigator.epubReadingSystem` object is underspecified, and here's an ongoing discussion about it:
https://github.com/IDPF/epub-revision/issues/474#issuecomment-94965005

Dan

**Comment by danielweck** [comment]
Regarding using prototype inheritance to "attach" a globally-available `epubReadingSystem` object: (`Navigator.prototype.epubReadingSystem`), here is a related article that shows how `iframe` (among other techniques) can be used to sandbox prototype extensions:
https://msdn.microsoft.com/en-us/magazine/gg278167.aspx
In other words, this is why we have to "manually" inject `epubReadingSystem` into each loading iframe.

**Comment by danielweck** [comment]
Fixed: https://github.com/readium/SDKLauncher-Android/commit/3f39e42040be601b20d0e3365a929798be1eeafb

**Comment by danielweck** [comment]
Thanks to @bluefire-cbond and @jdempcy for helping with this, and for testing on their end. In the end I decided to remove the synchronised object / semaphore altogether, because since I updated my KitKat ROM from a clean slate, I have been unable to consistently reproduce the navigator.epubReadingSystem delay issue (I have a low end device, but I can overclock or underclock to test different performance contexts). As page-load timeout is a critical problem, and as it seems that occurrences of late EPRS injection are rare, I think it is reasonable to remove the semaphore / locking object.
By the way, I should point out that in my tests I always make sure to check the behaviour in single iframes (single FXL page, or single/multiple reflowable pages), versus multiple iframes (two-page FXL spread): that's because `WebView:shouldInterceptRequest` is invoked *asynchronously* when there are several iframes involved (we can't actually use a thread lock on a per-iframe basis, which is why we end-up interlocking the main thread (race condition)).
