### ISSUE TITLE
Which version support MathML ? 

### ISSUE THREAD

**Issue by wzhsunn** [readium/SDKLauncher-Android#57]
I test win launcher but it dose not support mathml . 

https://code.google.com/p/epub-samples/downloads/detail?name=linear-algebra-20120306.epub&can=2&q=

**Comment by danielweck** [comment]
Duplicate, and wrong repository:
https://github.com/readium/SDKLauncher-Windows/issues/8

@wzhsunn the ReadiumSDK application launchers on iOS, OSX and Android all support MathML via MathJax (as well as ReadiumJS "cloud reader" and Chrome extension). However, SDKLauncher-Windows is behind the other platforms due to lack of development resources for this particular C++ MFC implementation. Sorry for the inconvenience.

**Comment by wzhsunn** [comment]
Thank you !
