### ISSUE TITLE
Using SDKLauncher-Android documentation

### ISSUE THREAD

**Issue by teddywest32** [readium/SDKLauncher-Android#70]
I am trying to use readium-sdk for my project but i am unable to use it as a library project. I couldnot find the implementation documentation of readium. Can i know how to integrate the sdk using any of eclipse or Android Studio.  Thanks.

**Comment by danielweck** [comment]
First of all, are you able to compile + run/debug the SDKLauncher-Android app? Are you on Windows / Linux / OSX? (the native readium-sdk NDK build is notoriously difficult to achieve on Windows, but it should be easy on Linux and OSX)

**Comment by teddywest32** [comment]
@danielweck  I am using windows and i am able to run ./ndk-compile.sh  build and generate <code>libepub3.so</code> and now how can i use it with my project.

**Comment by danielweck** [comment]
Okay, so I assume you are using Cygwin (?)

Next, you need to clone the `SDKLauncher-Android` Git repository, checkout the `develop` branch, and remember to initialise the `readium-sdk` and `readium-shared-js` Git submodules (sub-folders) so that the source tree is complete in your local copy. Take a look at the contents of the `SDKLauncher-Android/assets/readium-shared-js/builds/` folder, and let me know what you see:
https://github.com/readium/SDKLauncher-Android/tree/develop/SDKLauncher-Android/assets/readium-shared-js/builds
...on Cygwin ; depending on your Git configuration ; you might see the expanded files instead of the symbolic links ... otherwise you will have to copy the files manually from `SDKLauncher-Android/readium-shared-js/build-output/`

Then, just open the Eclipse projects (you can safely ignore the "test" project, just open the main app + the epub3-lib projects), and run/debug the app from there.

Once you have got these steps working fine, you will then be able to figure-out how to implement your own Readium-based application "front-end".

**Comment by teddywest32** [comment]
Thanks for the comment.
Yes, I am using Cygwin. 
I cloned the <code> SDKLauncher-Android master</code> with <code> recursive </code> command and cloned <code>readium-sdk</code>,<code>readium-shared-js</code> and <code>SDKLauncher-Android</code>.
Should I need to clone develop branch??
The contents of <code>SDKLauncher-Android/assets/readium-shared-js/builds/ </code> are:
1. css : ../../../../readium-shared-js/build-output/css/
2. multiple-bundles : ../../../../readium-shared-js/build-output/_multiple-bundles/
3. single-bundle  : ../../../../readium-shared-js/build-output/_single-bundle/

I couldn't find <code>readium-shared-js/build-output/</code> inside <code>SDKLauncher-Android</code>.

**Comment by danielweck** [comment]
Try this:
`git clone —recursive https://github.com/readium/SDKLauncher-Android.git –b develop SDKLauncher-Android`
`cd SDKLauncher-Android`
`git submodule update --init --recursive`
`git checkout develop && git submodule foreach --recursive "git checkout develop"`

**Comment by danielweck** [comment]
...then `SDKLauncher-Android/readium-shared-js` should contain all the required files in the `./build-output` folder. However, because of symbolic links in `SDKLauncher-Android/assets/readium-shared-js/builds/`, you might need to manually copy+paste the linked files (assuming Git-Cygwin did not already perform that step for you, of course).
