### ISSUE TITLE
self-developed DRM. Whether bulid

### ISSUE THREAD

**Issue by gibumkim** [readium/SDKLauncher-Android#99]
Hello ~!
READIUM SDK user.
Of course, yet testers.
Our company would like to use self-developed DRM.
But I'm not sure how
Can I get the source or hints?

**Comment by rkwright** [comment]
Regrettably we don't have any step-by-step instructions.  This document does outline in general how it can be done, but it assumes a pretty strong knowledge of Readium. In addition, I believe it is now somewhat out of date since we integrated LCP (which taught us a lot).

[drm-module-20131126.pdf](https://github.com/readium/SDKLauncher-Android/files/362311/drm-module-20131126.pdf)

**Comment by thkim2015** [comment]
@gibumkim

**Comment by danielweck** [comment]
Adding to @rkwright and @thkim2015 's already excellent contributions:
please take a look at this (slightly old, but still relevant) wiki page 
https://github.com/readium/readium-sdk/wiki/ContentFilterEncryptedMedia
